
import { AuditLog, AuditAction, ResourceType, AuditLogQuery } from './enterprise.types.js';

export class AuditLogService {
  private logs: AuditLog[] = [];

  /**
   * Creates an immutable audit log entry.
   */
  public createAuditLog(
    organizationId: string, 
    userId: string, 
    action: AuditAction, 
    resourceType: ResourceType, 
    resourceId: string, 
    workspaceId?: string, 
    metadata?: Record<string, any>
  ): AuditLog {
    if (!organizationId || !userId || !action || !resourceType || !resourceId) {
      throw new Error('Missing required fields for audit log');
    }

    const log: AuditLog = {
      id: this.generateId('audit_'),
      organizationId,
      workspaceId,
      userId,
      action,
      resourceType,
      resourceId,
      timestamp: new Date().toISOString(),
      metadata: metadata || {}
    };

    this.logs.push(log);
    return log;
  }

  /**
   * Retrieves a specific audit log by ID.
   */
  public getAuditLog(auditLogId: string): AuditLog | null {
    return this.logs.find(log => log.id === auditLogId) || null;
  }

  /**
   * Queries audit logs based on provided filters.
   */
  public queryAuditLogs(query: AuditLogQuery): { logs: AuditLog[]; total: number; limit: number; offset: number } {
    let filtered = this.logs.filter(log => log.organizationId === query.organizationId);

    if (query.workspaceId) filtered = filtered.filter(log => log.workspaceId === query.workspaceId);
    if (query.userId) filtered = filtered.filter(log => log.userId === query.userId);
    if (query.action) filtered = filtered.filter(log => log.action === query.action);
    if (query.resourceType) filtered = filtered.filter(log => log.resourceType === query.resourceType);
    
    if (query.startDate) {
      const start = new Date(query.startDate).getTime();
      filtered = filtered.filter(log => new Date(log.timestamp).getTime() >= start);
    }
    if (query.endDate) {
      const end = new Date(query.endDate).getTime();
      filtered = filtered.filter(log => new Date(log.timestamp).getTime() <= end);
    }

    // Sort descending by timestamp
    filtered.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());

    const limit = query.limit || 100;
    const offset = query.offset || 0;
    const paginated = filtered.slice(offset, offset + limit);

    return {
      logs: paginated,
      total: filtered.length,
      limit,
      offset
    };
  }

  /**
   * Retrieves audit logs for an organization.
   */
  public getOrganizationAuditLogs(organizationId: string, limit: number = 100, offset: number = 0): AuditLog[] {
    return this.queryAuditLogs({ organizationId, limit, offset }).logs;
  }

  /**
   * Retrieves audit logs for a specific workspace.
   */
  public getWorkspaceAuditLogs(workspaceId: string, limit: number = 100, offset: number = 0): AuditLog[] {
    // Note: Requires organizationId in a real DB query, here we just filter the array
    const filtered = this.logs.filter(log => log.workspaceId === workspaceId);
    filtered.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
    return filtered.slice(offset, offset + limit);
  }

  /**
   * Retrieves audit logs generated by a specific user.
   */
  public getUserAuditLogs(userId: string, limit: number = 100, offset: number = 0): AuditLog[] {
    const filtered = this.logs.filter(log => log.userId === userId);
    filtered.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
    return filtered.slice(offset, offset + limit);
  }

  /**
   * Retrieves audit logs for a specific resource.
   */
  public getResourceAuditLogs(resourceType: ResourceType, resourceId: string): AuditLog[] {
    const filtered = this.logs.filter(log => log.resourceType === resourceType && log.resourceId === resourceId);
    filtered.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
    return filtered;
  }

  /**
   * Generates a summary of audit events for an organization over a period.
   */
  public getAuditSummary(organizationId: string, startDate?: string, endDate?: string): any {
    const queryResult = this.queryAuditLogs({ organizationId, startDate, endDate, limit: 10000 });
    const logs = queryResult.logs;

    const eventsByAction: Record<string, number> = {};
    const eventsByResourceType: Record<string, number> = {};
    const eventsByUser: Record<string, number> = {};

    logs.forEach(log => {
      eventsByAction[log.action] = (eventsByAction[log.action] || 0) + 1;
      eventsByResourceType[log.resourceType] = (eventsByResourceType[log.resourceType] || 0) + 1;
      eventsByUser[log.userId] = (eventsByUser[log.userId] || 0) + 1;
    });

    return {
      organizationId,
      totalEvents: logs.length,
      eventsByAction,
      eventsByResourceType,
      eventsByUser,
      period: { startDate, endDate }
    };
  }

  /**
   * Exports audit logs in the specified format.
   */
  public exportAuditLogs(organizationId: string, startDate?: string, endDate?: string, format: 'json' | 'csv' = 'json'): string {
    const logs = this.queryAuditLogs({ organizationId, startDate, endDate, limit: 10000 }).logs;
    
    if (format === 'csv') {
      return this.convertToCSV(logs);
    }
    
    return JSON.stringify(logs, null, 2);
  }

  /**
   * Helper to convert logs to CSV format.
   */
  private convertToCSV(logs: AuditLog[]): string {
    if (logs.length === 0) return '';
    
    const headers = ['id', 'timestamp', 'organizationId', 'workspaceId', 'userId', 'action', 'resourceType', 'resourceId'];
    const rows = logs.map(log => {
      return [
        log.id,
        log.timestamp,
        log.organizationId,
        log.workspaceId || '',
        log.userId,
        log.action,
        log.resourceType,
        log.resourceId
      ].map(val => `"${val}"`).join(',');
    });

    return [headers.join(','), ...rows].join('\n');
  }

  /**
   * Generates a unique ID with a specific prefix.
   */
  private generateId(prefix: string): string {
    return `${prefix}${Math.random().toString(36).substring(2, 15)}${Math.random().toString(36).substring(2, 15)}`;
  }
}
